### ISSUE TITLE
create javascript folder

### ISSUE THREAD

**Issue by Chifez** [ossamamehmood/Hacktoberfest2023#29]
create a folder for contributing javascript code and a readme.md file stating the contribution guidelines

**Comment by JeevaRamanathan** [comment]
I would like to work on this, pls assign to me

**Comment by MissAashnaa1** [comment]
Hi. please open more issues and assign to me

**Comment by Chifez** [comment]
> I would like to work on this, pls assign to me

alright

**Comment by Chifez** [comment]
> Hi. please open more issues and assign to me

@MissAashnaa1 if there is anything you would like to add to the repo to improve it,you can create an issue and if ok we can assign it to you
