### ISSUE TITLE
covid-traker

### ISSUE THREAD

**Issue by Manish4Kumar** [ossamamehmood/Hacktoberfest2023#4320]

**Comment by policeakshithreddy** [comment]
Would you kindly assign this task to me? I would greatly appreciate it.

**Comment by 457ayan** [comment]
Can I contribute your code

**Comment by 457ayan** [comment]
Please assign to contribute

**Comment by Ratikant-rout** [comment]
Can You Please Assing Me This Project I Would be So Much Glad To Contribute In This project

**Comment by Saket009** [comment]
Would you please assign this issue to me ? it will be much appreciated as I am new to open-source !!

**Comment by mishrayush15** [comment]
greetings,
could you please assign this task to me as I am fluent in C++, python, and Java and would happily contribute to open-source projects.

**Comment by vaibhavshukla06** [comment]
May I request you to assign this task to me? I would be very grateful for your consideration.

**Comment by AkshatJangid787** [comment]
Can You Please Assign Me This Project I Would be So Much Glad To Contribute In This project

**Comment by 457ayan** [comment]
completed

**Comment by Param129** [comment]
Would you please assign this issue to me ?

**Comment by Itzz-Ck** [comment]
Please assign the task to me .

**Comment by alipsa2000** [comment]
Hey @ossamamehmood can you please assign me this task?
