### ISSUE TITLE
No T-Shirts from now on

### ISSUE THREAD

**Issue by thieleju** [ossamamehmood/Hacktoberfest2023#4323]
Remove "- FREE T-SHIRT🎉" from Repository description.

Source:
https://hacktoberfest.com/about/#digital-rewards

**Comment by ossamamehmood** [comment]
That's pretty sad to hear we having no swag of contribution 😃

**Comment by thieleju** [comment]
Yeah, I didn't even get last years T-shirt because maintainers did not receive any (except for a handful)
Put a lot of time into [this project ](https://github.com/thieleju/statsbot) but no T-shirt, not even the digital badges

**Comment by SUBHAJITNANDI2002** [comment]
can you assign me for this issues?

**Comment by syed-muheed** [comment]
please assign this issue to me

**Comment by thieleju** [comment]
This was meant to be a issue for @ossamamehmood, the maintainer of the repository, because normal contributors can't change the repository description. 

Closing this as the "free t-shirt" seems intentional
