### ISSUE TITLE
I would like to add graph search algorithms i.e DFS and BFS code in python

### ISSUE THREAD

**Issue by Niyati3031** [ossamamehmood/Hacktoberfest2023#4417]
Can you please assign this to me for hacktoberfest 2023

**Comment by Tejoooo** [comment]
can u assign me this issue

**Comment by Ankitasen21** [comment]
U can assign me this

**Comment by Sweta-Raj31** [comment]
hey can you please assign this issue to me.

**Comment by SayaliMarathe-13** [comment]
Hello,
could you please assign it to me
