### ISSUE TITLE
i can add  solutions for majorly asked dsa questions 

### ISSUE THREAD

**Issue by PrasanBora** [ossamamehmood/Hacktoberfest2023#4419]

**Comment by imSanko** [comment]
Can I work in this issue

**Comment by diya2505** [comment]
Can you please assign this issue to me?

**Comment by Tejoooo** [comment]
can u assign me this issue

**Comment by AKG1301** [comment]
can u assign me this issue

@ossamamehmood

**Comment by chiku011** [comment]
Hello, I would like to request assignment to the  issue as I believe I can make a meaningful contribution to the project.

**Comment by kishan2510** [comment]
can u assign me this issue

**Comment by Itzz-Ck** [comment]
Hey, please please assign this task to me.
