### ISSUE TITLE
Detect and remove loops/cycle in linked list

### ISSUE THREAD

**Issue by PrathamDwivedi27** [ossamamehmood/Hacktoberfest2023#4420]
I will do this code in C++ by briefly explaining floyd detection cycle technique.
Please assign me this problem.

**Comment by 123suraj-sky** [comment]
Hi there, I am Suraj Kumar Yadav. I have studied DSA in a training program in BHU which is funded by government. This is my first time I am taking part in hacktoberfest. Can you please assign this problem?

**Comment by chiku011** [comment]
Hello, I would like to request assignment to the  issue as I believe I can make a meaningful contribution to the project.

**Comment by itzpiyushjindal** [comment]
"Excited to kickstart my Hacktoberfest journey by tackling the 'Detect and remove loops/cycle in linked list' issue! Ready to contribute and learn. Please assign me this problem.

**Comment by alipsa2000** [comment]
Hey @ossamamehmood please can you assign me this task?
