### ISSUE TITLE
N stacks in a array in c++

### ISSUE THREAD

**Issue by PrathamDwivedi27** [ossamamehmood/Hacktoberfest2023#4421]
Please assign this task to me. I will be happy to contribute

**Comment by PooniaPankaj** [comment]
hey, I am well versed with c++ and I would like to contribute in that one can you please assign it to me.

**Comment by Sweta-Raj31** [comment]
Hey can you please assign this issue to me.

**Comment by darshsingh116** [comment]
Opened a PR
