### ISSUE TITLE
sudoku_solver_cpp

### ISSUE THREAD

**Issue by nancy-singh10** [ossamamehmood/Hacktoberfest2023#4424]
plz assign me this project under hacktoberfest2023

**Comment by aman5062** [comment]
Yes i can create it . Assign me for fast response.

**Comment by chiku011** [comment]
Hello, I would like to request assignment to this issue as I believe I can make a meaningful contribution to the project.

**Comment by aniketmdinde** [comment]
plz assign me this

**Comment by Tyrant670** [comment]
Hey, I would like to contribute to this issue.
I'll code it in c++ with explanation.
Can you assign this one to me .

**Comment by Itzz-Ck** [comment]
Hey, I can solve this problem using CPP, as I have already done this one already in C lang and I can efficiently make the sudoku solver code in much efficient and interesting way.

So can you please assign this one to me.

**Comment by Modernbeast02** [comment]
Hey @ossamamehmood Can you please assign this to me?

**Comment by alipsa2000** [comment]
Hey @ossamamehmood  I request you to assign me this exciting task?

**Comment by Rbcoder1** [comment]
Hey @ossamamehmood Can your Please Assign It To Me
