### ISSUE TITLE
Want to add next greater element in stack code

### ISSUE THREAD

**Issue by jc8223** [ossamamehmood/Hacktoberfest2023#4446]
@ossamamehmood 
please provide me this privilege to contribute to this repository

**Comment by itzpiyushjindal** [comment]
"Thrilled to make my Hacktoberfest debut by taking on the 'Want to add next greater element in stack code' issue! Eager to contribute and grow with the community. Please assign me this task.

**Comment by jc8223** [comment]
#4493

**Comment by Sweta-Raj31** [comment]
Hey can please assign this issue to me.

**Comment by Itzz-Ck** [comment]
Hey can you please assign this issue to me, I can solve it in more efficient way

**Comment by Modernbeast02** [comment]
Hey @ossamamehmood Can you assign this to me?
