### ISSUE TITLE
update Readme.md

### ISSUE THREAD

**Issue by sharma62** [ossamamehmood/Hacktoberfest2023#4487]
### Readme.md file 
In Readme.md file has 3 tasks completed by the contributor & then merged.
 - Add your profile information
 
![Screenshot (55)](https://github.com/ossamamehmood/Hacktoberfest2023/assets/75290099/ea29cfa5-0441-4ac1-8a0f-f1b2f6e7b0ae)

> After update 
- update   - Add your profile information 
 separate sections and contributors are easy to contribute.

**Comment by sharma62** [comment]
@ossamamehmood I really glad to resolve this issue.

**Comment by AkshatJangid787** [comment]
i want to resolve this

**Comment by Unknown-Cypher** [comment]
Can you assign this task to me too
