### ISSUE TITLE
TwoSum

### ISSUE THREAD

**Issue by Namya13Jain** [ossamamehmood/Hacktoberfest2023#4497]
Pls assign me this issue. I'll add the code in C++ language.

**Comment by Tyrant670** [comment]
Hey, I want to contribute to this issue.
I'll code it in several languages and update it so can assign this issue to me.

**Comment by PooniaPankaj** [comment]
Hey, I am well versed with c++ and I would like to contribute in that can you please assign it to me .

**Comment by Sweta-Raj31** [comment]
Hey can you please assign this issue to me.

**Comment by kadamprashant1** [comment]
hey can you assign this issue to me?

**Comment by RahaneSayali** [comment]
hey, i would like to contribute. Could you please assign this isssue to me
