### ISSUE TITLE
Implementing Stack using Queue

### ISSUE THREAD

**Issue by Arpcoder** [ossamamehmood/Hacktoberfest2023#4500]
Please assign this to me for Hacktoberfest.

**Comment by Tyrant670** [comment]
Hey, I would like to contribute here!
Can you assign this one to me.

**Comment by PooniaPankaj** [comment]
Hey, I am well versed with c++ and I would like to contribute in that one  can you please assign it to me.

**Comment by Arpcoder** [comment]
@Tyrant670 , @PooniaPankaj  Hii...You can open ur own issue and contribute to that...New Issue green button is available at right side...From there u can create ur own issues

**Comment by kadamprashant1** [comment]
hey I am new here but I can solve your issue clearly. Can you assign this issue to me?

**Comment by alipsa2000** [comment]
Sir Can you please assign me this issue?

**Comment by Rbcoder1** [comment]
Please Assign It To Me
