### ISSUE TITLE
Add dynamic programming leetcode questions difficulty wise (Hacktoberfest '23)

### ISSUE THREAD

**Issue by sujanrupu** [ossamamehmood/Hacktoberfest2023#4507]
As a **Hacktoberfest '23** contributor I would like to add a series of questions on dynamic programming from Leetcode separated difficulty wise.

No of questions: Approx 15
Language: C++

**Comment by parasvekariya26** [comment]
plz assign this issue

**Comment by Sweta-Raj31** [comment]
Hey can please assign this issue to me.
