### ISSUE TITLE
⚠ EXCLUDED From HacktoberFest 2023 

### ISSUE THREAD

**Issue by cu-sanjay** [ossamamehmood/Hacktoberfest2023#4513]
Hello Everyone, please note that this repository is excluded from **HacktoberFest 2023**, and your contributions will not be counted for the event.
![image](https://github.com/ossamamehmood/Hacktoberfest2023/assets/96792511/8a795f13-e878-4e48-b666-9c9b6c288382)

**Comment by Soumojitshome2023** [comment]
use hacktoberfest-accepted label :)
