### ISSUE TITLE
I want to add some most useful algorithms code Like --

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [ossamamehmood/Hacktoberfest2023#4531]
1)  K-way merge Algorithm

2) Stack Reduced Quick Sort

3) Merge sort combined with Insertion Sort

4) Prims, Topological, Kruskal's algorithm

5) DijKstra , Floyd Warshall ,bellman ford algorithm

6) Backtracking 
     a) Rat Maze
     b) N-Queen
    c) Sudoku
    d) Sum of Subset

7) Activity selection , Huffman Encoding .

**Comment by Gyanshu-Kumar** [comment]
Hello Sir Please assign this issue to me

**Comment by Bharath-KumarReddy** [comment]
Hello Greatings,
Issue #4531 is assigned to me .

As i just resolved the problem
Adding most useful algorithms

Please provide me access rights to make a pull request : )
