### ISSUE TITLE
Add Spaces Leetcode problem

### ISSUE THREAD

**Issue by ayan-joshi** [ossamamehmood/Hacktoberfest2023#4629]
To add a leetcode problem named Add Spaces ,
This question ask us to add spaces in a string , so it's a string funnction problem 

Please assign me this issue @ossamamehmood under hacktoberfest label

**Comment by Ankitasen21** [comment]
Please assign me this issue

**Comment by ayan-joshi** [comment]
Guys I'm also contributor , Please find some other issues , leave this one for me

**Comment by adityaxcix01** [comment]
assign me this one pls
