### ISSUE TITLE
House Robber III in C++

### ISSUE THREAD

**Issue by uday-kiran-001** [ossamamehmood/Hacktoberfest2023#4651]
I want to add House Robber III Leetcode solution in C++

**Comment by sparshstark** [comment]
Hii @uday-kiran-001, Please assign me this issue !!
Regards,

**Comment by ManavTanna** [comment]
Please assign the issue to me @uday-kiran-001

**Comment by bhaveshgarg2000** [comment]
Please assign this issue to me

**Comment by RishabB54** [comment]
Please assign the issue to me @uday-kiran-001
