### ISSUE TITLE
Repository is excluded from Hacktoberfest 2023

### ISSUE THREAD

**Issue by AvidCoder101** [ossamamehmood/Hacktoberfest2023#4666]
@ossamamehmood It seems as though this repository is excluded from Hacktoberfest:

![image](https://github.com/ossamamehmood/Hacktoberfest2023/assets/70807684/a79bbefb-46fa-4413-b1cd-26fbc4918518)

**Comment by zulfikar-ditya** [comment]
@ossamamehmood Same here
