### ISSUE TITLE
Selection sort in CPP

### ISSUE THREAD

**Issue by Vyshnavi21504** [ossamamehmood/Hacktoberfest2023#4700]
I'm Vyshnavi . I want to add selection sort in cpp under Hacktoberfest2023 .Pls assign me this issue.

**Comment by abhayanand08** [comment]
Hey @ossamamehmood kindly assign this issue to me. I can give a great solution for this.

**Comment by kartikey-singh-k** [comment]
i want  to work on this kindly assign me

**Comment by akshaydubey05** [comment]
Hey @ossamamehmood  Please assign this task to me i want to contribute in this task .

**Comment by yellurividyendra** [comment]
Subject: Request for Selection Sort Implementation Task

Body:
Dear @ossamamehmood ,
I am eager to contribute to the project and am particularly interested in the Selection Sort implementation task in C++. I have strong C++ skills and sorting algorithm experience.
Assigning me this task would not only benefit the project but also enhance my practical understanding of sorting algorithms. I assure timely completion and high-quality work.
Looking forward to collaborating with the team.
Best regards,
[Yelluri Vidyendra]
[iit2022057@iiitl.ac.in]

**Comment by abhayanand08** [comment]
Hey @ossamamehmood kindly assign this issue to me. I can give a great solution for this.

**Comment by anupam-singh88** [comment]
hey @ossamamehmood kindly assign me to this task.

**Comment by indianguy123** [comment]
hey @ossamamehmood can you please assign me this task. I want to brush up my programming skills.

**Comment by Aryan741x** [comment]
Hello, @ossamamehmood  Please give me the following assignment. I am quite knowledgeable with DSA and technology sorting.

**Comment by adityaxcix01** [comment]
pls assign me buddy

**Comment by Himanshu66109** [comment]
Hello, @ossamamehmood Please assign me this issue.

**Comment by Chandanmali** [comment]
Hello, @ossamamehmood Please assign me this issue.
