### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by archit2311** [ossamamehmood/Hacktoberfest2023#4701]
Hi,

I want to add the C++ code for Median of two sorted arrays with the most efficient approach along with comments and explanation.

Please assign me this issue.

**Comment by Ankitasen21** [comment]
Assign me this issue I have code ready in C++, Java

**Comment by SAYAN042** [comment]
assign me this issue I want to contribute in this problem with efficient approach

**Comment by vixxhesh** [comment]
Assign me this issue which can I contribute using divide and conquer method.

**Comment by yellurividyendra** [comment]
Subject: Request for Median of Two Sorted Arrays Task

Body:
Dear @archit2311 ,
I am interested in the task concerning the median of two sorted arrays. With strong problem-solving skills and algorithmic expertise, I am eager to contribute. Please consider assigning me this task.

Best,
[Yelluri Vidyendra]
[iit2022057@iiitl.ac.in]

**Comment by ADNAAN18** [comment]
Hello, 
Please assign me this issue to which I can contribute. Also, I can provide the code in different programming languages, starting from the brute force approach to the optimized approach with proper explanations so that others would understand much faster and clearly.

Regards,
Adnaan.

**Comment by indianguy123** [comment]
hey @ossamamehmood I wanted to contribute in this issue. i have the most effecient code ready for it.

**Comment by adityaxcix01** [comment]
assign me pls

**Comment by ADNAAN18** [comment]
@ossamamehmood sir I accidentally clicked unassign option could you please re-assign me.
