### ISSUE TITLE
My contribution gets excluded idk

### ISSUE THREAD

**Issue by kondapalli19** [ossamamehmood/Hacktoberfest2023#4730]

**Comment by kondapalli19** [comment]
![Screenshot 2023-10-01 195305](https://github.com/ossamamehmood/Hacktoberfest2023/assets/101511737/444b8d5b-5ed0-4ad2-8e22-9f7fbaf0e098)

**Comment by vaishnavitnaik** [comment]
it's the same for me, because this repo is excluded from hacktoberfest. Maybe we should try another one.

**Comment by dev1abhi** [comment]
Why did it get excluded??

**Comment by vaishnavitnaik** [comment]
no idea!! there are certain rules for maintainers on the site, ig maybe it violates or misses out on some points.
Maybe the owner can check and resolve it.
