### ISSUE TITLE
Adding Solution of "30 Days Of Javascript from LeetCode"

### ISSUE THREAD

**Issue by utsxvrai** [ossamamehmood/Hacktoberfest2023#4746]
Hello,

I'd like to propose adding a new issue to this project where I'll provide solutions to the "30 Days of JavaScript" challenges from LeetCode. I believe this would be a valuable addition to the project and can help others learn and practice JavaScript.

I'm willing to take ownership of this issue and regularly contribute solutions for each challenge, along with explanations. Please consider creating the issue, and I'll start working on it immediately.

Thank you for considering my proposal.

Best regards,
[Utsav Rai]

**Comment by utsxvrai** [comment]
pls assign this issue @ossamamehmood to me

**Comment by adityaxcix01** [comment]
pls assign me

**Comment by Chandanmali** [comment]
pls assign this issue @ossamamehmood to me
