### ISSUE TITLE
regarding hacktober

### ISSUE THREAD

**Issue by PrasanBora** [ossamamehmood/Hacktoberfest2023#4813]
its still not showing in my hacktober

**Comment by vaishnavitnaik** [comment]
same.  Does it show that this repo is excluded?

**Comment by dev1abhi** [comment]
Yes, It's still showing as excluded.

**Comment by vaishnavitnaik** [comment]
if you look at the rules, then might find the reason why it is excluded.
it says: BAD REPOSITORIES WILL BE EXCLUDED.
PR/MRs should be useful to maintainers. Repos that encourage simplistic PR/MRs (like adding a name or profile to a list or arbitrarily curating content) will be excluded from Hacktoberfest. Remember: quantity is fun, quality is key.

**Comment by dev1abhi** [comment]
> if you look at the rules, then might find the reason why it is excluded. it says: BAD REPOSITORIES WILL BE EXCLUDED. PR/MRs should be useful to maintainers. Repos that encourage simplistic PR/MRs (like adding a name or profile to a list or arbitrarily curating content) will be excluded from Hacktoberfest. Remember: quantity is fun, quality is key.

Not necessarily tho , coz over the last years , many repositories with same idea/concept have been qualified under hacktoberfest. it's for promoting open-source spirits for newbies to just get started with prs.

**Comment by Yashbhatti3325** [comment]
I also got that same problem in my PR/MR.

**Comment by TYehan** [comment]
Same here.
![image](https://github.com/ossamamehmood/Hacktoberfest2023/assets/85949077/df83acf6-7175-4f6f-98d5-3017f61ba969)

Maintainers should add the CONTRIBUTING.md into the repo
