### ISSUE TITLE
Sudoku Solver Problem using backtracking in Java

### ISSUE THREAD

**Issue by Spardha-hash** [ossamamehmood/Hacktoberfest2023#4884]
I want to add the solution of sudoku solver problem using backtracking approach in Java. Please assign this issue to me @ossamamehmood.

**Comment by Aryan741x** [comment]
HI, @ossamamehmood  I would Like to add the solution of sudoku solver using backtracking . Kindly assign the issue to me._

**Comment by Aditya-132** [comment]
i would like to solve this problem

**Comment by draksham** [comment]
I have done this problem before i would like to add the solution for that problem it would be a pleasure for me if you assign the issue to me

**Comment by shivamk23** [comment]
let me do this
