### ISSUE TITLE
Linear Search Algorithm 

### ISSUE THREAD

**Issue by Vyshnavi21504** [ossamamehmood/Hacktoberfest2023#4887]
Hi , Im Vyshnavi . I want to add Linear Search Algorithm in cpp .pls assign me this issue

**Comment by Abdul25Basit** [comment]
hey it would be glad if you assign me this issue

**Comment by Aryan741x** [comment]
Hey i would like to add Linear Search Algorithm. Kindly Assign the issue to me

**Comment by pawas108ram** [comment]
Hey I would like this to be assigned to me.I can also provide the adequate instructions and some test examples

**Comment by KirtiPandey19** [comment]
Please assign this issue to me.

**Comment by Aditya-132** [comment]
Please assign me this issue

**Comment by Abhi-goyal1** [comment]
please assign me this

**Comment by MahakGautam2002** [comment]
Hey Hi,
I can create Write code for all searching algorithm.
Can I Contribute for this issue?
please assign it to me

**Comment by srushtikage** [comment]
hello, can you please assign me this issue.

**Comment by Shobhit0603** [comment]
As an active participant in Hacktoberfest, I am eager to take on the assigned issue. I bring with me a commitment to optimizing solutions with the finest space and time complexities. Rest assured, your task is in capable hands. Please assign this issue to me.

**Comment by yashraj4823** [comment]
Hello , Can you please assign this issue to me?? I have already worked on the code. Please assign this issue to me to work under Hacktoberfest 2023.
