### ISSUE TITLE
Want to Add Infix to Postfix Program in C

### ISSUE THREAD

**Issue by AkshatJangid787** [ossamamehmood/Hacktoberfest2023#4895]

**Comment by Anju-Narnolia** [comment]
I want to work on this issue.P;ease assign it to me

**Comment by KirtiPandey19** [comment]
Please assign this issue to me

**Comment by ujjwalshivhare** [comment]
Hello Sir,
can you assign me this issue?

**Comment by tejpatil064** [comment]
Hello sir,  I can easily handle this issue. Can u please assign it to me?
