### ISSUE TITLE
Want to add most asked binary search questions in companies

### ISSUE THREAD

**Issue by Harsh-91221** [ossamamehmood/Hacktoberfest2023#4909]
I am Harsh Kumar,please assign this task to me

**Comment by Sachinsharmak** [comment]
Hi Can you Please assign this to me

**Comment by Kritikmahajan** [comment]
@Harsh-91221 assign me this issue , I will be adding 3 or more most asked binary search questions with the testcases. 
and plz add hacktoberfest tag to it also.
