### ISSUE TITLE
I can add a c++ code to find number of Distinct Subsequence in a String.

### ISSUE THREAD

**Issue by saurav806** [ossamamehmood/Hacktoberfest2023#4959]
Given a string consisting of lower case English alphabets, the task is to find the number of distinct subsequences of the string
Note: Answer can be very large, so, ouput will be answer modulo 109+7.

Input: 
s = "abc"
Output: 
8
Explanation: 
The seven distinct subsequences are "", "a", "ab", "ac", "abc", "b", "bc" and "c" .

**Comment by MahakGautam2002** [comment]
Hey Hi,
I can create Write code for this issue.
Can I Contribute for this issue?
please assign it to me

**Comment by aish7iitkgp** [comment]
Hi,
I have experience in solving these kind of problems, can I write a code for this issue.
I would like to contribute to this issue.
please assign the issue to me.
