### ISSUE TITLE
Longest Consecutive Sequences [ Leetcode ]

### ISSUE THREAD

**Issue by UG-SEP** [ossamamehmood/Hacktoberfest2023#5036]
Problem statement:

```
Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence.

Input: nums = [100,4,200,1,3,2]
Output: 4
```

- My program time complexity: O(N)
- Space complexity: O(N)
- Language: C++

@ossamamehmood **Kindly assign me the issue** 

Thank you

**Comment by Debaditya-Som** [comment]
@UG-SEP , can we add DSA and leetcode problems in this repo?

**Comment by UG-SEP** [comment]
> @UG-SEP , can we add DSA and leetcode problems in this repo?

Yes @Debaditya-Som
Folder are created to add the Leetcode problem solution

**Comment by mrinalproxy** [comment]
Can You assign me this issue @UG-SEP

**Comment by srushtikage** [comment]
Hello, can you please assign me this issue.
