### ISSUE TITLE
String is palindrome or not? interview question.

### ISSUE THREAD

**Issue by kadamprashant1** [ossamamehmood/Hacktoberfest2023#5038]
I can solve this issue with various ways to solve the same problem. As per the interview approach. Can I solve this issue?

**Comment by vinay1033** [comment]
I contribute to issue. Just tell me , Do I have to create file or it is already in repository?

**Comment by puran2003gupta** [comment]
Hello , can you assign this issue to me.

**Comment by srushtikage** [comment]
Hello, can you please assign this issue to me I want to contribute this issue.

**Comment by Shobhit0603** [comment]
As an active participant in Hacktoberfest, I am eager to take on the assigned issue. I bring with me a commitment to optimizing solutions with the finest space and time complexities. Rest assured, your task is in capable hands. Please assign this issue to me.

**Comment by ujjwalshivhare** [comment]
Hello Sir ,
can you assign me this issue .
