### ISSUE TITLE
This repo is EXCLUDED from Hacktoberfest 2023

### ISSUE THREAD

**Issue by TYehan** [ossamamehmood/Hacktoberfest2023#5072]
Maintainers, Please consider this.
@ossamamehmood

**Comment by prashantkalokhe** [comment]
Why

**Comment by TYehan** [comment]
There is no CONTRIBUTING.md in repo

**Comment by Debaditya-Som** [comment]
![image](https://github.com/fineanmol/Hacktoberfest2023/assets/121785700/0ff7b75b-8f6c-4165-98a2-466f6c6fe30f)

Same here

**Comment by sharma62** [comment]
any solution for this
