### ISSUE TITLE
Find Minimum in  Rotated Sorted Array

### ISSUE THREAD

**Issue by hsayvaidya23** [ossamamehmood/Hacktoberfest2023#5124]
Suppose an array of length n sorted in ascending order is rotated between 1 and n times. For example, the array nums = [0,1,2,4,5,6,7] might become:

 [4,5,6,7,0,1,2] if it was rotated 4 times.
 [0,1,2,4,5,6,7] if it was rotated 7 times.
 Notice that rotating an array [a[0], a[1], a[2], ..., a[n-1]] 1 time results in the array [a[n-1], a[0], a[1], a[2], ..., a[n-2]].

 Given the sorted rotated array nums of unique elements, return the minimum element of this array.

 You must write an algorithm that runs in O(log n) time.

**Comment by sahilbheke** [comment]
Hello @hsayvaidya23 want to work on this issue and it's my first time in open source but not in programming. So, Can you help with this.

**Comment by Shiwani5** [comment]
Hi Sir, I Hope you are doing well. As this is my first time participating in the open source challenge, I know the most optimized solution for this code. Please permit me to solve this problem.

**Comment by harshsingh32** [comment]
Please assign this issue to me under hacktoberfest23.
