### ISSUE TITLE
Binary Search Using Recursion

### ISSUE THREAD

**Issue by pabitra0011** [ossamamehmood/Hacktoberfest2023#5128]
Learn basics of Recursion through A simple problem Binary Search

**Comment by Shiwani5** [comment]
Hi Sir, I Hope you are doing well. As this is my first time participating in the open source challenge, I know the most optimized solution for this code. Please permit me to solve this problem.

**Comment by pabitra0011** [comment]
Sure! and good luck for your first contribution.👩‍💻👍
