### ISSUE TITLE
Factorial of a number N using Recursion.

### ISSUE THREAD

**Issue by pabitra0011** [ossamamehmood/Hacktoberfest2023#5133]
The most common basics and first problem for understanding recursion and recurrence  relation.

**Comment by STRIZERORTIX** [comment]
Could you assign this Issue to me? I've already completed and I'm waiting for PR

**Comment by Rohankr18** [comment]
I can solve it.....

**Comment by jayprakash6547** [comment]
can you please assign this issue to me
