### ISSUE TITLE
No free T-shirts this year; update needed

### ISSUE THREAD

**Issue by Mrk-Mzj** [ossamamehmood/Hacktoberfest2023#5246]
Hacktoberfest organizers have dropped the shipping of T-shirts this year. They moved to [digital rewards](https://hacktoberfest.com/about/#digital-rewards) instead.

Free T-shirt information should be removed from:

- [x] About
- [x] tags
- [x] README.md (in three places)

**Comment by Jigisha160** [comment]
hey I am Jigisha 
Can you assign this work to me

**Comment by divyansh2375** [comment]
i would like to work on this issue . can you please assign this task to me . I can create issue ticket if you want

**Comment by inbuilt-aura** [comment]
Hey @Mrk-Mzj, can i contribute on this issue?

**Comment by Mrk-Mzj** [comment]
I'm a regular contributor, just like you all. I'm not assigning issues. You can ask @ossamamehmood or work right away on a pull request.

**Comment by Suraj-kumar00** [comment]
> I'm a regular contributor, just like you all. I'm not assigning issues. You can ask @ossamamehmood or work right away on a pull request.

Hi @Mrk-Mzj, so you please tell me like why you created this issue like on the behalf of maintainer of this repository or something like I want know or you have created this is issue to work yourself and get you pull request merged? May I know please!!!

**Comment by Mrk-Mzj** [comment]
> Hi @Mrk-Mzj, so you please tell me like why you created this issue like on the behalf of maintainer of this repository or something like I want know or you have created this is issue to work yourself and get you pull request merged? May I know please!!!

I noticed the problem and created an issue, but I am not working on it. 

I see that you asked Ossama to assign - that's a good idea. However, there are repositories where issues are assigned to specific people, but in others this is not practiced. I do not know how it is here - I did not find this information.

It seems that at the moment there is no pull request that solves this problem. Or at least there is no PR that has the number of this issue in the title. Otherwise we would have a mention of it here.

Since we don't know if issues are assigned to specific people - I, if I were you, would make changes, set up a pull request with the title ".... fixes #5246" and that would clarify the situation. :)

**Comment by TYehan** [comment]
Well if someone knows take this repo out from the EXCLUDED ones. Because this repo is already excluded from the Hacktoberfest 2023.

**Comment by inbuilt-aura** [comment]
@TYehan wait what excluded?

**Comment by TYehan** [comment]
Yeah. 
![image](https://github.com/ossamamehmood/Hacktoberfest2023/assets/85949077/c15dcf3e-2fe5-4d34-9150-00173690a73a)

### Issues regarding this.
#4813 
#5072

**Comment by TYehan** [comment]
> @TYehan wait what excluded?

Yeah. 
![image](https://github.com/ossamamehmood/Hacktoberfest2023/assets/85949077/c15dcf3e-2fe5-4d34-9150-00173690a73a)

### Issues regarding this.
#4813 
#5072

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by anshul-132002** [comment]
Heyy @Mrk-Mzj   I want to work on this issue. Please assign it to me.

**Comment by anshul-132002** [comment]
pls merge my pull request
