### ISSUE TITLE
Beautiful Towers 2

### ISSUE THREAD

**Issue by sahilbheke** [ossamamehmood/Hacktoberfest2023#5253]
You are given a 0-indexed array maxHeights of n integers.

You are tasked with building n towers in the coordinate line. The ith tower is built at coordinate i and has a height of heights[i].

A configuration of towers is beautiful if the following conditions hold:

1 <= heights[i] <= maxHeights[i]
heights is a mountain array.
Array heights is a mountain if there exists an index i such that:

For all 0 < j <= i, heights[j - 1] <= heights[j]
For all i <= k < n - 1, heights[k + 1] <= heights[k]
Return the maximum possible sum of heights of a beautiful configuration of towers.

**Comment by draksham** [comment]
I want to work on this issue can you please assign it to me

**Comment by draksham** [comment]
def maxSumOfHeights(heights, maxHeights):
    n = len(heights)
    
   
    dp = [[0, 0] for _ in range(n)]
    
   
    dp[0][0] = heights[0]  
    dp[0][1] = 0           
    
    
    for i in range(1, n):
        
        dp[i][0] = max(dp[i-1][0], dp[i-1][1]) + heights[i]
        
        
        dp[i][1] = max(dp[i-1][0] - maxHeights[i-1], dp[i-1][1])
    
    
    return max(dp[n-1][0], dp[n-1][1])


heights = [1, 3, 5, 2, 4]
maxHeights = [2, 1, 7, 5, 6]
result = maxSumOfHeights(heights, maxHeights)
print(result)  
I have completed this issue

**Comment by kartikey-singh-k** [comment]
I want to work on this issue kindly assign me

**Comment by Kd-Here** [comment]
Can I work on it?
Could you assign?

**Comment by SanaSultana1234** [comment]
Please assign this issue to me.

**Comment by aish7iitkgp** [comment]
I know the most optimised solution for this issue, please assign this issue to me.

**Comment by exeayush18** [comment]
hey @ossamamehmood i want to work on this code ..do assign me too

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by adit2005** [comment]
Hi @ossamamehmood Having solved 300+ questions on Leetcode I would be able to contribute most optimized code for this with explanation. I request you to pls assign me this.

**Comment by Ratna2** [comment]
@ossamamehmood I want to work on this issue. Please assign me this

**Comment by draksham** [comment]
Hi @ossamamehmood once check my pull request i have added the file
