### ISSUE TITLE
Reverse The String using stack in C

### ISSUE THREAD

**Issue by AkshatJangid787** [ossamamehmood/Hacktoberfest2023#5294]

**Comment by draksham** [comment]
I want to work on this issue it would be a glad for me if u assign it to me

**Comment by draksham** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


struct Stack {
    int top;
    unsigned capacity;
    char* array;
};


struct Stack* createStack(unsigned capacity) {
    struct Stack* stack = (struct Stack*)malloc(sizeof(struct Stack));
    stack->capacity = capacity;
    stack->top = -1;
    stack->array = (char*)malloc(stack->capacity * sizeof(char));
    return stack;
}


int isEmpty(struct Stack* stack) {
    return stack->top == -1;
}


void push(struct Stack* stack, char item) {
    stack->array[++stack->top] = item;
}


char pop(struct Stack* stack) {
    if (!isEmpty(stack)) {
        return stack->array[stack->top--];
    }
    return '\0'; 
}


void reverseString(char* input) {
    int len = strlen(input);

    
    struct Stack* stack = createStack(len);

    
    for (int i = 0; i < len; i++) {
        push(stack, input[i]);
    }

    
    for (int i = 0; i < len; i++) {
        input[i] = pop(stack);
    }
}

int main() {
    char input[100];

    printf("Enter a string: ");
    scanf("%s", input);

    reverseString(input);

    printf("Reversed string: %s\n", input);

    return 0;
}

**Comment by SanaSultana1234** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by pinak01** [comment]
I am interested in taking on the task at hand and want to assure you that I will complete it to the best of my ability. I kindly request that you assign this task to me.

**Comment by samraj-freak** [comment]
I am interested in this task. please aaisn me

**Comment by aish7iitkgp** [comment]
I would be able to write optimised code for this issue, please assign this to me.

**Comment by Ratna2** [comment]
I want to work on this issue. Please assign me

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by SONUKUMARRAM145** [comment]
hey pls assign this issue to me , i want to contribute on this issue

**Comment by Ratna2** [comment]
@ossamamehmood  pls assign this issue to me . I want to do this

**Comment by draksham** [comment]
Hey @ossamamehmood Once check my PR I have added the code for Reverse the string using stack in c

**Comment by yogeshbansal7** [comment]
@ossamamehmood please assign this to me

**Comment by Ishika0-0** [comment]
@ossamamehmood Can you please let me contribute to this issue
