### ISSUE TITLE
This repo has been excluded from the hacktoberfest 2023

### ISSUE THREAD

**Issue by UG-SEP** [ossamamehmood/Hacktoberfest2023#5298]
Kindly update this to the readme file @ossamamehmood 

![Screenshot 2023-10-03 215730](https://github.com/ossamamehmood/Hacktoberfest2023/assets/75884061/33d3d665-d342-4493-99d3-f62ac37f9a27)

**Comment by Nirzak** [comment]
Yeah +1. This has been excluded from hacktoberfest 2023!

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by fatimashaikh04** [comment]
same here

**Comment by ossamamehmood** [comment]
Assigned all of you guys please fix it asap

**Comment by Nirzak** [comment]
> Assigned all of you guys please fix it asap
I don’t think it’s a fixable issue as the repo has been excluded by the hacktoberfest committee! Requesting on their discord group may not work!

**Comment by UG-SEP** [comment]
> > Assigned all of you guys please fix it asap
> > I don’t think it’s a fixable issue as the repo has been excluded by the hacktoberfest committee! Requesting on their discord group may not work!

True😂

**Comment by ossamamehmood** [comment]
Can someone of you guys request it? 😅
