### ISSUE TITLE
Readme file excluded from Hacktoberfest 2023

### ISSUE THREAD

**Issue by ikunal-04** [ossamamehmood/Hacktoberfest2023#5329]
Please add the readme file also in hacktoberfest 2023:

![image](https://github.com/ossamamehmood/Hacktoberfest2023/assets/112847288/f62ee3ae-c271-4b6e-bc22-ea8f6dcca0ce)

**Comment by HarshikaAdarsh** [comment]
Hey @ikunal-04 I'm interested in working on it. Would it be possible to assign this issue to me?

**Comment by ikunal-04** [comment]
Hii @HarshikaAdarsh actually I have already fixed this error I'm myself asking maintainer @ossamamehmood to label my pr as hacktoberfest accepted

**Comment by HarshikaAdarsh** [comment]
> Hii @HarshikaAdarsh actually I have already fixed this error I'm myself asking maintainer @ossamamehmood to label my pr as hacktoberfest accepted

Okay

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by ikunal-04** [comment]
> Hii @HarshikaAdarsh actually I have already fixed this error I'm myself asking maintainer @ossamamehmood to label my pr as hacktoberfest accepted

.. @Ashima2003

**Comment by ossamamehmood** [comment]
Do it a fix !!

**Comment by ossamamehmood** [comment]
I have assigned everyone please come up with a fix for that!

**Comment by ikunal-04** [comment]
@ossamamehmood I fixed this issue in #5328 pull request

**Comment by anshul-132002** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by sethisagar** [comment]
Hey I want to work on this issue. Please assign it to me.

**Comment by ikunal-04** [comment]
@ossamamehmood my pr is excluded from hacktoberfest and I don't know what's the reason? could you please help me with that and let me know what might be the possible reason?
