### ISSUE TITLE
STACK implementation in C

### ISSUE THREAD

**Issue by jain-anshika** [ossamamehmood/Hacktoberfest2023#5332]
There no code of stack implementation in c language.

**Comment by exeayush18** [comment]
hey @ossamamehmood i would like to contribute in this... do assign me !

**Comment by jain-anshika** [comment]
@ossamamehmood  I think I created the issues first so it should be assigned to me only...!

**Comment by Ratna2** [comment]
@ossamamehmood i am a very skiklled c programer. Assign this issue to me

**Comment by harshamogra** [comment]
@ossamamehmood please assign this to me .. i will contribute an efficient code

**Comment by kmnat** [comment]
@ossamamehmood could you please assign the issue to me please

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by adit2005** [comment]
Hi @ossamamehmood Pls assign this to me . Having solved 300+ problems on Leetcode I would like to contribute to this.

**Comment by SONUKUMARRAM145** [comment]
hey pls assign this issue to me , i want to work on this issue thankyou

**Comment by Joshna907** [comment]
@ossamamehmood Hey, I'm good in dsa so I want to work on this issue, Please assign it to me.

**Comment by vilasrhegde** [comment]
Please assign me this issue

**Comment by yogeshbansal7** [comment]
please assign me this issue

**Comment by Ayush-Garg1** [comment]
@ossamamehmood Please assign this issue to me.
I assure you with a good outcome....
