### ISSUE TITLE
Pattern programs in C

### ISSUE THREAD

**Issue by jain-anshika** [ossamamehmood/Hacktoberfest2023#5333]
I have done many pattern programs in c language.

**Comment by Jatingupta9120** [comment]
please assign this issue to me

**Comment by draksham** [comment]
It would be a glad for me if you assign this issue to me

**Comment by ich-tanishqa** [comment]
Please assign this issue to me

**Comment by rishirohilla** [comment]
please assign this to me

**Comment by VBPMP** [comment]
Assign me this duty, please.

**Comment by MazeJack** [comment]
Hello Sir, Can you assign me this issue?

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by SONUKUMARRAM145** [comment]
hey @ossamamehmood  pls assign this issue to me , i want to contribute

**Comment by draksham** [comment]
Hey @ossamamehmood Once check my PR I have added the code for the pattern programs in c

**Comment by Joshna907** [comment]
Hi @ossamamehmood  I think I can work my best as dsa is my strength, Plz assign this to me

**Comment by anshul-132002** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by Sanskar1002** [comment]
hey @ossamamehmood please assign it to me

**Comment by Ishika0-0** [comment]
@ossamamehmood Can I contribute to this issue

**Comment by Meyor0Code** [comment]
I would be glad if I'm assigned this Issue @ossamamehmood

**Comment by VBPMP** [comment]
I have worked on this issue @ossamamehmood Please, check the pull request

**Comment by mifrasgaffoor** [comment]
Heyy I want to work on this issue. Please assign it to me @jain-anshika
