### ISSUE TITLE
Prim's and Kruskal's Algo in C++

### ISSUE THREAD

**Issue by kmnat** [ossamamehmood/Hacktoberfest2023#5382]
@ossamamehmood please assign this issue to me

**Comment by HarshikaAdarsh** [comment]
Hey @ossamamehmood, I'm interested in working on it. Would it be possible to assign this issue to me?

**Comment by draksham** [comment]
Hey @ossamamehmood I would like to work on this issue can you please assign it to me

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by adit2005** [comment]
Hi @ossamamehmood I would like to contribute to this. I will not only add code but also proper explanation for it. I request you to Pls assign me this.

**Comment by SONUKUMARRAM145** [comment]
hey pls assign this issue to me , i want to work on this issue thankyou

**Comment by draksham** [comment]
Hey @ossamamehmood once check my PR I have added the codes for prims Algorithm and kruskals Algorithm

**Comment by panditakshay402** [comment]
Hi @ossamamehmood , Kindly Assign this issue  to me , I want to contribute with best i have.

**Comment by Joshna907** [comment]
Hey @ossamamehmood I would like to contribute

**Comment by yogeshbansal7** [comment]
@ossamamehmood please assign this to me

**Comment by HarshikaAdarsh** [comment]
Hey @ossamamehmood I have worked on this issue. kindly check the pull request and if possible then merge it also.

**Comment by Shreyas250503** [comment]
Hey @ossamamehmood, I am interested. Could you please assign it to me.

**Comment by Arnav7107** [comment]
Hey @ossamamehmood I would love to contribute to this. Can you please assign me?

**Comment by Bikash0007** [comment]
Please assign me this issue under hacktoberfest 2023.
