### ISSUE TITLE
Sorting Techniques in JAVA

### ISSUE THREAD

**Issue by Humaira-Sadia** [ossamamehmood/Hacktoberfest2023#5428]
Hello @ossamamehmood, I would like to create efficient Java programs for all types of sorting techniques of Data Structure, including :

1. Selection Sort, 
2. Bubble Sort,
3. Insertion Sort,
4. Heap Sort,
5. Merge Sort,
6. Quick Sort 

to make it easier for beginners to learn and help in understanding it better.

**Comment by Humaira-Sadia** [comment]
Hey @ossamamehmood, it would be my great pleasure to work on this repo  :)
Could you please assign this issue to me?

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by tusharkumar19701** [comment]
#5441 Sorting Algorithm in Java added

**Comment by tusharkumar19701** [comment]
Please merge it under Hacktoberfest-accepted label

**Comment by anshul-132002** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by SonaliHalder** [comment]
I want to work on this issue. Please assign it to me.

**Comment by tusharkumar19701** [comment]
#5441 Added all sorting algorithms

**Comment by Pratham271** [comment]
I also want to contribute to it

**Comment by Bikash0007** [comment]
Please assign me this issue under hacktoberfest 2023.

**Comment by Shiwani5** [comment]
Hi, I Hope you are doing well. This is my first contribution to an open challenge contribution platform. I know the solution to this please assign this to me so that I can contribute.

**Comment by Rajnikant9835** [comment]
Can I solve this issue ?

**Comment by mehakbasrani** [comment]
I want to contribute. Can you please assign it to me
