### ISSUE TITLE
Leet Code sol for cpp

### ISSUE THREAD

**Issue by aryanksanghvi** [ossamamehmood/Hacktoberfest2023#5431]
For problem 1929 - merge array
For problem 1672 - Max wealth of owner
I would like to add the solutions for these under Hactoberfest 2023
please assign me

**Comment by draksham** [comment]
Hey @aryanksanghvi i want to work on this issue can you please assign it to me

**Comment by aryanksanghvi** [comment]
I am not the one assigning, I myself want it assigned to me.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by Joshna907** [comment]
I want to work on this issue @ossamamehmood Please assign it to me

**Comment by SonaliHalder** [comment]
i would like to work on this issue . can you please assign this task to me . I can create issue ticket if you want

**Comment by SonaliHalder** [comment]
i would like to work on this issue . can you please assign this task to me . I can create issue ticket if you want

**Comment by Joshna907** [comment]
I have worked on this issue @ossamamehmood  Please, check the pull request

**Comment by siddharth687** [comment]
Hey, @ossamamehmood I have created a pull request, Please check and approve it

**Comment by chinmay7016** [comment]
Hi @ossamamehmood pls assign me this

**Comment by Abhip2109** [comment]
Hii @ossamamehmood I would like to contribute in this , so kindly assign me this

**Comment by RiyaRanka** [comment]
Hello, Under Hacktoberfest2023, I want to work under this issue. Please assign me.

**Comment by aryanksanghvi** [comment]
Hey, I have created a PR for the same. Kindly accept it, as I was assigned this task
