### ISSUE TITLE
kahn's algorithm in c++

### ISSUE THREAD

**Issue by anjalii14** [ossamamehmood/Hacktoberfest2023#5440]
Please me assign me this issue. I want to contribute for graph directory.

**Comment by Joshna907** [comment]
Please assign me this issue @ossamamehmood

**Comment by Bikash0007** [comment]
Please assign me this issue under hacktoberfest 2023.

**Comment by mehakbasrani** [comment]
I want to contribute. Please assign

**Comment by chinmay7016** [comment]
Pls 🙏 assign me this I also want to contribute
