### ISSUE TITLE
Cube Root in Python

### ISSUE THREAD

**Issue by HarshChhikara** [ossamamehmood/Hacktoberfest2023#5454]
Hey @ossamamehmood  I would like to work on this issue. Please assign this to me.

**Comment by gauravmandall** [comment]
@ossamamehmood Assign this issue to me

**Comment by SonaliHalder** [comment]
i would like to work on this issue . can you please assign this task to me .

**Comment by vilasrhegde** [comment]
I would like to work on this. Please assign me

**Comment by TechWizard9999** [comment]
@ossamamehmood  I am intrested in this issue 
Please assign me this iseu and please label it under HAcktober fest

**Comment by foolhardys** [comment]
Please Assign me the issue

**Comment by Pratham271** [comment]
Assign it to me also

**Comment by Bikash0007** [comment]
Please assign me this issue under hacktoberfest 2023.

**Comment by AditiMishra2003** [comment]
I would like to solve this issue if you assign it to me :)

**Comment by sammyifelse** [comment]
plz assign this issue to me
