### ISSUE TITLE
Face Mask Detection using Python and Computer Vision

### ISSUE THREAD

**Issue by RitwikGanguly** [ossamamehmood/Hacktoberfest2023#5480]
@ossamamehmood I want to add the face mask detection project using computer vision and python, which is a real life project.
please assign me into this project.

**Comment by Bikash0007** [comment]
please assign me into this project under hacktoberfest 2023

**Comment by riddhi-283** [comment]
I request you to please assign this to me under Hacktoberfest 2023

**Comment by RitwikGanguly** [comment]
added the project of face mask recognition in this repo at #5648 

@ossamamehmood please merge the project and add all tags.
