### ISSUE TITLE
Migrating code to TypeScript

### ISSUE THREAD

**Issue by shvam0000** [ossamamehmood/Hacktoberfest2023#5526]
Would love to start migrating JavaScript code to TypeScript.

Would love to start with a simple BinarySearch file (https://github.com/ossamamehmood/Hacktoberfest2023/blob/main/Add%20Code%20Here/Javascript/Binary%20Search.js).

**Comment by shvam0000** [comment]
Please assign this to me and I would like to do it under hacktoberfest label.

**Comment by Groot-2001** [comment]
hey @ossamamehmood i would love to contribute to this issue if you confirm that if there is other problems that need to migrate from js to typescript under hackthoberfest label!?
