### ISSUE TITLE
LeetCode 75 Solutions

### ISSUE THREAD

**Issue by Shrimad-Bhagwat** [ossamamehmood/Hacktoberfest2023#5650]
## Add your solutions for the LeetCode 75 🎯 plan.

🧑‍💻Create seperate folders for different languages and upload your best solution with explanation.

Link🔗 : https://leetcode.com/studyplan/leetcode-75/

**Comment by Shrimad-Bhagwat** [comment]
Hi @ossamamehmood, I would like to work on this issue. Can you please assign this task to me.

**Comment by Harsh-91221** [comment]
Hey, @ossamamehmood I would like to contribute and work on this issue

**Comment by utkarshmajumdar12** [comment]
Hi @ossamamehmood I would like to contribute and work in this issue, kindly assign me this task.

**Comment by chinmay7016** [comment]
Hi @ossamamehmood I would like to contribute and work in this issue, kindly pls assign me this task.

**Comment by yogeshbansal7** [comment]
Please assign this issue to me
