### ISSUE TITLE
Clock using Html,Css,Javascript

### ISSUE THREAD

**Issue by MohammadAsiya** [ossamamehmood/Hacktoberfest2023#5660]
I would like to add new project Clock using Html,css,javascript Please assign this issue to me under Hacktoberfest2023

**Comment by Joshna907** [comment]
hi @ossamamehmood I would like to contribute

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by shivam200446** [comment]
Hey, I want to work on it assign me!

**Comment by mehakbasrani** [comment]
I want to contribute. Please assign

**Comment by muskanv021** [comment]
hello ,
please assign to me this task .
I would like to contribute .

**Comment by shivam200446** [comment]
please open the issue and review @ossamamehmood
