### ISSUE TITLE
frontened-intereview-question

### ISSUE THREAD

**Issue by jatingodnani** [ossamamehmood/Hacktoberfest2023#5676]
All type of question asked in   frontened-inverview including machine level coding question.
@ossamamehmood add hacktoberfest tag in this

**Comment by jatingodnani** [comment]
assign to me

**Comment by muskanv021** [comment]
Hello sir,
Please assign to me this task .

**Comment by jatingodnani** [comment]
check this @ossamamehmood

**Comment by jatingodnani** [comment]
@ossamamehmood check my pr

**Comment by jatingodnani** [comment]
Why you have closed this @ossamamehmood.any specific reason
