### ISSUE TITLE
Adding Dynamic Queue

### ISSUE THREAD

**Issue by susanhsrestha** [ossamamehmood/Hacktoberfest2023#57]
For the addition of dynamic queue with the help of linked list.

**Comment by susanhsrestha** [comment]
@Chifez #43

**Comment by Chifez** [comment]
assigning this task you @susanhsrestha

**Comment by susanhsrestha** [comment]
Can you review this, #43 ?

**Comment by tausifaman222** [comment]
@Chifez What shall be the best language to work on it ?
