### ISSUE TITLE
You need to stop this spam. ASAP!

### ISSUE THREAD

**Issue by ShivamJoker** [ossamamehmood/Hacktoberfest2023#5801]
### Whatever you're doing is unethical and goes against open source community.
You're encouraging spam for getting free T-Shirt and goodies.

### Kindly delete or archive the repo.
> Else you'll be reported and banned from GitHub.

**Comment by ossamamehmood** [comment]
The report is already excluded and there no t-shirt 👕 at all this season!

**Comment by ShivamJoker** [comment]
@ossamamehmood doesn't matter. You need to stop this.
Don't use such cheap tactics to gain followers and useless stars.

**Comment by ossamamehmood** [comment]
Hmmm 🤔! Thanks for letting me.

Will think about it today and sign ✍️ get to conclusion!

**Comment by ShivamJoker** [comment]
You need to stop replying using ChatGPT!
Just archive the repo if you don't want your account to be suspended.

**Comment by ossamamehmood** [comment]
Who been using chatGPT 

Can you please tell me what's you point of interaction here!! 

If I said that I'll look upon today so why you are pretending to disturb someone again and again?
