### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by blindaks** [ossamamehmood/Hacktoberfest2023#5814]
Add URL Shortener
Tech Stack:
HTML
CSS
JavaScript

**Comment by blindaks** [comment]
Please assign this issue to me.

**Comment by draksham** [comment]
I would like to work on this issue can you please assign it to me

**Comment by blindaks** [comment]
Hey @ossamamehmood , do I need to first raise an issue for a contribution, or can I make a pr directly?
