### ISSUE TITLE
Add Linked list code

### ISSUE THREAD

**Issue by Mahikagarg09** [ossamamehmood/Hacktoberfest2023#5896]
Adding Linked list code having -

- class for linked list
- functions for insertion
- functions for deletion
- function for reversing linked list
- function for checking if linked list is palindrome
- function for finding middle node of linked list

Please assign this issue to me.

**Comment by ayushiGautam-0110** [comment]
please assign this issue to me... I would like to contribute to it

**Comment by Ishika0-0** [comment]
@ossamamehmood Can I contribute to #5967 issue I have some experience in this topic

**Comment by rahulmangla28** [comment]
Please assign this issue to me.
