### ISSUE TITLE
Dungeon Game in JavaScript using Dynamic Programming

### ISSUE THREAD

**Issue by Robinrai2612** [ossamamehmood/Hacktoberfest2023#5900]
The demons had captured the princess and imprisoned her in the bottom-right corner of a dungeon. The dungeon consists of m x n rooms laid out in a 2D grid. Our valiant knight was initially positioned in the top-left room and must fight his way through dungeon to rescue the princess.

The knight has an initial health point represented by a positive integer. If at any point his health point drops to 0 or below, he dies immediately.

Some of the rooms are guarded by demons (represented by negative integers), so the knight loses health upon entering these rooms; other rooms are either empty (represented as 0) or contain magic orbs that increase the knight's health (represented by positive integers).

To reach the princess as quickly as possible, the knight decides to move only rightward or downward in each step.

Return the knight's minimum initial health so that he can rescue the princess.

Input: dungeon = [[-2,-3,3],[-5,-10,1],[10,30,-5]]
Output: 7
Explanation: The initial health of the knight must be at least 7 if he follows the optimal path: RIGHT-> RIGHT -> DOWN -> DOWN.

@ossamamehmood I would like to work on this issue. Please assign this issue to me.

**Comment by Somil-Shukla** [comment]
please assign this issue to me

**Comment by rahulmangla28** [comment]
Please assign this issue to me.
