### ISSUE TITLE
Merge two sorted Linked Lists

### ISSUE THREAD

**Issue by shanvijha30** [ossamamehmood/Hacktoberfest2023#5987]
Given two singly linked lists that are sorted in increasing order of node values, merge two sorted linked lists and return them as a sorted list. The list should be made by splicing together the nodes of the first two lists.

Language: Java

**Comment by shanvijha30** [comment]
@ossamamehmood I would like to work on this issue under Hacktoberfest 2023. Could you please assign it to me.
Thank you!

**Comment by kartikey-singh-k** [comment]
i want to work on this issue kindly allow me

**Comment by Ankurgour** [comment]
@ossamamehmood I want to contribute to your issue kindly allow me.
Thank You!!

**Comment by iPriyanshu19** [comment]
@ossamamehmood I would like to work on this issue under Hacktoberfest 2023. Could you please assign it to me.
Thank you

**Comment by chinmay7016** [comment]
@ossamamehmood pls assign me
