### ISSUE TITLE
Add Odd-Even Sort / Brick Sort

### ISSUE THREAD

**Issue by shanvijha30** [ossamamehmood/Hacktoberfest2023#5989]
Odd-Even Sort / Brick Sort :
This algorithm is divided into two phases- Odd and Even Phase. The algorithm runs until the array elements are sorted and in each iteration two phases occurs- Odd and Even Phases.

Feature :
Add Odd-Even Sort / Brick Sort in Python.

Description of solution :
Will add Odd-Even Sort / Brick Sort with adequate comments and proper documentation for readers to get a clear understanding.
To be added in Java.

Alternatives Considered :
Could you please assign me this issue under Hacktoberfest 2023.

**Comment by shanvijha30** [comment]
@ossamamehmood I would like to work on this issue . Could you please assign it to me.
Thank you!

**Comment by mayankgongal5** [comment]
can you please assign it to me.

**Comment by kmanishprogrammar** [comment]
please assign this to me as i would like to work on it

**Comment by chinmay7016** [comment]
@ossamamehmood pls assign me
