### ISSUE TITLE
Adding The code of Prim's and Kruskal Algorithm in cpp

### ISSUE THREAD

**Issue by Soumya6Tiwari** [ossamamehmood/Hacktoberfest2023#6153]

**Comment by AshBakchod** [comment]
Hey @Soumya6Tiwari i can help you with the code of Prim's and Kruskal Algorithm in C++

**Comment by AckermanLevi1** [comment]
@Soumya6Tiwari I would love to contribute in it

**Comment by snehpr966** [comment]
Hey please assign would like to contribute
