### ISSUE TITLE
To factorial.py source code 

### ISSUE THREAD

**Issue by yashwanths814** [ossamamehmood/Hacktoberfest2023#616]
Rather than using n, we can use specific name that is more understandable.

**Comment by ranya17-bit** [comment]
can you elaborate a bit more on the issue?

**Comment by yashwanths814** [comment]
by giving specific name. Like nonnagetive_integer. That name it self specifys it nature.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.
