### ISSUE TITLE
Hi... I'm a begineer in hacktoberfest

### ISSUE THREAD

**Issue by mizzcode** [ossamamehmood/Hacktoberfest2023#92]
can I contribute to this repo, especially in web development?

I will create a project Landing Page for Car Rental, please @Chifez  assign it to me under #hacktoberfest-accepted label

thanks...

**Comment by Mrk-Mzj** [comment]
@mizzcode This repository has been excluded from Hacktoberfest too. You can contribute, but won't get a Hacktoberfest badge.
